### ISSUE TITLE
PhpStormと同列の静的解析って出来ない？

### ISSUE THREAD

**Issue by osamu2001** [zonuexe/emacs-php-info#10]
同列の定義曖昧

**Comment by zonuexe** [comment]
「同列の」だとPhpStormと同じようにｸﾞｲｰﾝｸﾞｲｰﾝとバックグラウンドプロセスとファンを回しまくらないといけないので、もうちょっと省エネにいけないかなとふんわり思ってます。

**Comment by zonuexe** [comment]
Phan + Flycheckで(PhpStormほどではないものの)いい感じになる。

<img width="875" alt="2017-10-17 6 08 47" src="https://user-images.githubusercontent.com/822086/31657036-5ff3e256-b368-11e7-996a-1924de303668.png">

バックグラウンドプロセスを明示的に起動するのめんどくさいので、どうにか透過的にやりたい。
